os: Visual Studio 2017
environment:
  snk_secret:
    secure: 0l0TrDvCNXH4z922G/Qa5hFG4+4payl1zRAfjMfEXRw=

install:
  - dotnet restore

build:
  project: NGettext.sln

test_script:
  - cd test\NGettext.Tests
  - dotnet test -f netcoreapp1.0 && dotnet test -f netcoreapp2.0
  - cd ..\..
  - cd test\NGettext.PluralCompile.Tests
  - dotnet test -f netcoreapp1.0 && dotnet test -f netcoreapp2.0
